<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Address;

class AddressSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('addresses')->insert([
            [
                'id' => 1,
                'street' => 'Main Street',
                'number' => 123,
                'box' => 2,
                'postal_code' => 1000,
                'city' => 'Brussels',
                'province' => 'Brussels',
                'country' => 'Belgium',
                'type' => 'house',
                'is_billing_address' => 1,
            ],
            [
                'id' => 2,
                'street' => 'Oak Avenue',
                'number' => 456,
                'box' => 'B',
                'postal_code' => 2000,
                'city' => 'Antwerp',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'appartment',
                'is_billing_address' => 1,
            ],
            [
                'id' => 3,
                'street' => 'Vrijdagmarkt',
                'number' => 22,
                'box' => 5,
                'postal_code' => 9000,
                'city' => 'Ghent',
                'province' => 'East Flanders',
                'country' => 'Belgium',
                'type' => 'house',
                'is_billing_address' => 1,
            ],
            [
                'id' => 4,
                'street' => 'Bondgenotenlaan',
                'number' => 15,
                'box' => 3,
                'postal_code' => 3000,
                'city' => 'Leuven',
                'province' => 'Flemish Brabant',
                'country' => 'Belgium',
                'type' => 'house',
                'is_billing_address' => 1,
            ],
            [
                'id' => 5,
                'street' => 'Meir',
                'number' => 66,
                'box' => 7,
                'postal_code' => 2000,
                'city' => 'Antwerp',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'appartment',
                'is_billing_address' => 1,
            ],
            [
                'id' => 6,
                'street' => 'Mechelsesteenweg',
                'number' => 27,
                'box' => 10,
                'postal_code' => 2550,
                'city' => 'Kontich',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'appartment',
                'is_billing_address' => 0,
            ],
            [
                'id' => 7,
                'street' => 'Bruul',
                'number' => 10,
                'box' => 15,
                'postal_code' => 2800,
                'city' => 'Mechelen',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'appartment',
                'is_billing_address' => 1,
            ],
            [
                'id' => 8,
                'street' => 'Bredeheide',
                'number' => 13,
                'box' => 8,
                'postal_code' => 2860,
                'city' => 'Sint-Katelijne-Waver',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'house',
                'is_billing_address' => 1,
            ],
            [
                'id' => 9,
                'street' => 'Wilsonstraat',
                'number' => 70,
                'box' => 8,
                'postal_code' => 2860,
                'city' => 'Sint-Katelijne-Waver',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'house',
                'is_billing_address' => 1,
            ],
            [
                'id' => 10,
                'street' => 'Mechelsesteenweg',
                'number' => 21,
                'box' => 8,
                'postal_code' => 2860,
                'city' => 'Sint-Katelijne-Waver',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'house',
                'is_billing_address' => 1,
            ],
            [ /* landlord first address */
                'id' => 11,
                'street' => 'Schorenshof',
                'number' => 12,
                'box' => 0,
                'postal_code' => 3012,
                'city' => 'Leuven',
                'province' => 'Flemish Brabant',
                'country' => 'Belgium',
                'type' => 'appartment',
                'is_billing_address' => 0,
            ],
            [ /* first address renters */
                'id' => 12,
                'street' => 'Schorenshof',
                'number' => 12,
                'box' => 501,
                'postal_code' => 3012,
                'city' => 'Leuven',
                'province' => 'Flemish Brabant',
                'country' => 'Belgium',
                'type' => 'appartment',
                'is_billing_address' => 1,
            ],
            [
                'id' => 13,
                'street' => 'Schorenshof',
                'number' => 12,
                'box' => 503,
                'postal_code' => 3012,
                'city' => 'Leuven',
                'province' => 'Flemish Brabant',
                'country' => 'Belgium',
                'type' => 'appartment',
                'is_billing_address' => 1,
            ],
            [ /* landlord second address */
                'id' => 14,
                'street' => 'Zeebruggestraat',
                'number' => 34,
                'box' => 0,
                'postal_code' => 2500,
                'city' => 'Lier',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'appartment',
                'is_billing_address' => 0,
            ],
            [ /* second address renters */
                'id' => 15,
                'street' => 'Zeebruggestraat',
                'number' => 34,
                'box' => 101,
                'postal_code' => 2500,
                'city' => 'Lier',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'appartment',
                'is_billing_address' => 1,
            ],
            [
                'id' => 16,
                'street' => 'Zeebruggestraat',
                'number' => 34,
                'box' => 201,
                'postal_code' => 2500,
                'city' => 'Lier',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'appartment',
                'is_billing_address' => 1,
            ],
            [ /* old people */
                'id' => 17,
                'street' => 'Kapelstraat',
                'number' => 91,
                'box' => 91,
                'postal_code' => 2570,
                'city' => 'Duffel',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'house',
                'is_billing_address' => 1,
            ],
            [
                'id' => 18,
                'street' => 'Violetstraat',
                'number' => 21,
                'box' => 21,
                'postal_code' => 2440,
                'city' => 'Geel',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'house',
                'is_billing_address' => 1,
            ],
            [ /* lazy people */
                'id' => 19,
                'street' => 'Schoutetstraat',
                'number' => 8,
                'box' => 8,
                'postal_code' => 2800,
                'city' => 'Mechelen',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'house',
                'is_billing_address' => 1,
            ],
            [
                'id' => 20,
                'street' => 'Tuinbouwstraat',
                'number' => 20,
                'box' => 20,
                'postal_code' => 2800,
                'city' => 'Mechelen',
                'province' => 'Antwerp',
                'country' => 'Belgium',
                'type' => 'house',
                'is_billing_address' => 1,
            ],
            [ /* landlord personal address */
                'id' => 21,
                'street' => 'Grand Place',
                'number' => 1,
                'box' => 0,
                'postal_code' => 1000,
                'city' => 'Brussels',
                'province' => 'Brussels',
                'country' => 'Belgium',
                'type' => 'appartment',
                'is_billing_address' => 1,
            ],
            [ /* placeholder for meter allocation */
                'id' => 1000,
                'street' => 'Nowhere',
                'number' => 20,
                'box' => 4,
                'postal_code' => 5000,
                'city' => 'Charleroi',
                'province' => 'Brabant',
                'country' => 'Belgium',
                'type' => 'house',
                'is_billing_address' => 1,
            ]
        ]);
    }
}
