<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    public function run()
    {
        function generatePhone(){
            $phone = '047' . rand(0,9) . ' ' . sprintf("%03d", rand(0, 999)) . ' ' . sprintf("%03d", rand(0, 999));
            return $phone;
        }

        function generateDate(){
            $minBirthdate = Carbon::now()->subYears(18)->endOfDay();
            $maxBirthdate = Carbon::now()->endOfDay();

            $birthDate = Carbon::createFromTimestamp(rand($minBirthdate->timestamp, $maxBirthdate->timestamp));

            $birthDate = $birthDate->subYears(18);

            return $birthDate->toDateString();
        }

        DB::table('users')->insert([
            [   //Employee
                'id' => 1,
                'username' => 'bob',
                'first_name' => 'Bob',
                'last_name' => 'Doe',
                'password' => Hash::make('bob'),
                'employee_profile_id' => 1,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'bob@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [   //Employee
                'id' => 2,
                'username' => 'jef',
                'first_name' => 'jef',
                'last_name' => 'Doe',
                'password' => Hash::make('jef'),
                'employee_profile_id' => 2,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'jef@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [   //Employee who's Customer
                'id' => 3,
                'username' => 'kim',
                'first_name' => 'Kim',
                'last_name' => 'Doe',
                'password' => Hash::make('kim'),
                'employee_profile_id' => 3,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'kim@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [   //Commercial Customer
                'id' => 4,
                'username' => 'emily',
                'first_name' => 'Emily',
                'last_name' => 'Doe',
                'password' => Hash::make('emily'),
                'employee_profile_id' => null,
                'is_company' => 1,
                'company_name' => 'ABC comp.',
                'email' => 'emily@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [   //Residential Customer
                'id' => 5,
                'username' => 'ann',
                'first_name' => 'Ann',
                'last_name' => 'Doe',
                'password' => Hash::make('ann'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'ann@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [   
                'id' => 6,
                'username' => 'marie',
                'first_name' => 'Marie',
                'last_name' => 'Doe',
                'password' => Hash::make('marie'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'marie@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [   
                'id' => 7,
                'username' => 'mark',
                'first_name' => 'Mark',
                'last_name' => 'Doe',
                'password' => Hash::make('mark'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'mark@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [   
                'id' => 8,
                'username' => 'rob',
                'first_name' => 'Rob',
                'last_name' => 'Doe',
                'password' => Hash::make('rob'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'rob@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [
                'id' => 9,
                'username' => 'jan',
                'first_name' => 'Jan',
                'last_name' => 'Doe',
                'password' => Hash::make('jan'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'jan@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [
                'id' => 10,
                'username' => 'landlord',
                'first_name' => 'Landlord',
                'last_name' => 'Doe',
                'password' => Hash::make('landlord'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'landlord@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 1,
                'index_method' => 'website'
            ],
            [
                'id' => 11,
                'username' => 'rent1',
                'first_name' => 'Renter',
                'last_name' => 'One',
                'password' => Hash::make('rent1'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'rent1@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [
                'id' => 12,
                'username' => 'rent2',
                'first_name' => 'Renter',
                'last_name' => 'Two',
                'password' => Hash::make('rent2'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'rent2@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 0,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [
                'id' => 13,
                'username' => 'rent3',
                'first_name' => 'Renter',
                'last_name' => 'Three',
                'password' => Hash::make('rent2'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'rent3@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [
                'id' => 14,
                'username' => 'rent4',
                'first_name' => 'Renter',
                'last_name' => 'Four',
                'password' => Hash::make('rent2'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'rent4@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [
                'id' => 15,
                'username' => 'oldie',
                'first_name' => 'Old',
                'last_name' => 'Man',
                'password' => Hash::make('oldie'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'oldman@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'paper'
            ],
            [
                'id' => 16,
                'username' => 'goldie',
                'first_name' => 'Older',
                'last_name' => 'Woman',
                'password' => Hash::make('goldie'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'olderwoman@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'paper'
            ],
            [
                'id' => 17,
                'username' => 'lazy',
                'first_name' => 'Lazy',
                'last_name' => 'Person',
                'password' => Hash::make('lazy'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'lazy@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [
                'id' => 18,
                'username' => 'verylazy',
                'first_name' => 'VeryLazy',
                'last_name' => 'Person',
                'password' => Hash::make('lazy'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'verylazy@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [
                'id' => 19,
                'username' => 'rent5',
                'first_name' => 'New Renter',
                'last_name' => 'Five',
                'password' => Hash::make('rent5'),
                'employee_profile_id' => null,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'rentnew@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Belgian',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
            [
                'id' => 1000,
                'username' => 'undefined',
                'first_name' => 'Not Defined',
                'last_name' => '',
                'password' => Hash::make('undefined'),
                'employee_profile_id' => 1000,
                'is_company' => 0,
                'company_name' => null,
                'email' => 'undefined@gmail.com',
                'phone_nbr' => generatePhone(),
                'birth_date' => generateDate(),
                'nationality' => 'Dutch',
                'changed_default' => 1,
                'is_active' => 1,
                'is_landlord' => 0,
                'index_method' => 'website'
            ],
        ]);
    }
}
